spring:
  application:
    name: likeBasketBall
  config:
    import: security-variable.yml
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likebasketballProject?serverTimezone=Asia/Seoul
    username: root
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.apiKey}
            redirect-uri: ${kakao.redirect-uri}
            client-secret: ${kakao.client-secret}
            scope:
              - nickname
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: post
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: kauth.kakao.com
            token-uri: kauth.kakao.com
            user-info-uri: kapi.kakao.com
            user-name-attribute: email
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

server:
  tomcat:
    max-http-form-post-size: 300000000





mybatis:
  configuration:
    map-underscore-to-camel-case: true

